name: flutter_helper
description: helper repository that any flutter app needs
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1