name: flutter_helper
description: helper repository that any flutter app needs
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  quiver: ^3.2.1
  intl: '>=0.17.0'

dev_dependencies:
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1

#  very_good_analysis: ^3.1.0